// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEU0cf5UhAz0p0a3J3GSH4Tf3MO5YG55M',
    appId: '1:992878783135:web:b2e5d10cce239435e2d0aa',
    messagingSenderId: '992878783135',
    projectId: 'instagramapp-6f5a8',
    authDomain: 'instagramapp-6f5a8.firebaseapp.com',
    storageBucket: 'instagramapp-6f5a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCEOJ8ks_QLU1EeSpHTACv6kPsHqZ3Go',
    appId: '1:992878783135:android:d76dcf7c87b28289e2d0aa',
    messagingSenderId: '992878783135',
    projectId: 'instagramapp-6f5a8',
    storageBucket: 'instagramapp-6f5a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwVuMAaybYJyDwDet56Dskc1ZTKrWft5A',
    appId: '1:992878783135:ios:71a8bbb77dee45a6e2d0aa',
    messagingSenderId: '992878783135',
    projectId: 'instagramapp-6f5a8',
    storageBucket: 'instagramapp-6f5a8.appspot.com',
    iosBundleId: 'com.example.instagramapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwVuMAaybYJyDwDet56Dskc1ZTKrWft5A',
    appId: '1:992878783135:ios:71a8bbb77dee45a6e2d0aa',
    messagingSenderId: '992878783135',
    projectId: 'instagramapp-6f5a8',
    storageBucket: 'instagramapp-6f5a8.appspot.com',
    iosBundleId: 'com.example.instagramapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEU0cf5UhAz0p0a3J3GSH4Tf3MO5YG55M',
    appId: '1:992878783135:web:25efe16d9b24e3b2e2d0aa',
    messagingSenderId: '992878783135',
    projectId: 'instagramapp-6f5a8',
    authDomain: 'instagramapp-6f5a8.firebaseapp.com',
    storageBucket: 'instagramapp-6f5a8.appspot.com',
  );

}